executable = /home/$(whoami)/neutrino_interaction_CNN/singularity_files/singularity_wrapper.sh
arguments  = /home/$(whoami)/neutrino_interaction_CNN/singularity_files/v14_latest.sif python3.6 /home/$(whoami)/neutrino_interaction_CNN/main/train/train_nn.py
output     = train_nn_cpu.out
error      = train_nn_cpu.err
log        = train_nn_cpu.log
getenv     = True

request_cpus   = 4
request_memory = 16 GB

Requirements = TARGET.vm_name == "its-u20-nfs-20210413"

queue 
