executable = /home/sthoma31/neutrino_interaction_images/array_generator/train_nn/singularity_wrapper.sh
arguments  = /home/sthoma31/v14_latest.sif python3.6 /home/sthoma31/neutrino_interaction_images/array_generator/train_nn/dwmodel1/train_take1.py
output     = dwmodel.out
error      = dwmodel.err
log        = dwmodel.log
getenv     = True

request_cpus   = 4
request_memory = 16 GB

Requirements = TARGET.vm_name == "its-u20-nfs-20210413"

queue 
